# version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    networks:
      - incep-net
    volumes:
      - db_data:/var/lib/mysql
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - incep-net
    volumes:
      - wp_data:/var/www/wordpress
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - incep-net
    volumes:
      - wp_data:/var/www/wordpress
networks:
  incep-net:
    driver: bridge
volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mait-taj/data/mariadb
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mait-taj/data/wordpress
