services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:42
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress:42
    depends_on:
      - mariadb
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wp_data:/var/www/wordpress
  nginx:
    build: ./requirements/nginx
    image: nginx:42
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    depends_on:
      - wordpress
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wp_data:/var/www/wordpress

volumes:
  wp_data:
    name : wp_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/mait-taj/data/wordpress"
  db_data:
    name : db_data
    driver: local
    driver_opts:
      type: none 
      o: bind
      device: "/home/mait-taj/data/mysql"
networks:
  inception:
    name: inception