services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - db_data:/var/lib/mysql
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    restart: always
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wp_data:/var/www/wordpress
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    depends_on:
      - wordpress
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wp_data:/var/www/wordpress

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "/home/mait-taj/data/wordpress"
  db_data:
    driver: local
    driver_opts:
      type: bind 
      o: bind
      device: "/home/mait-taj/data/mysql"
networks:
  inception:
    name: inception
    driver: bridge